
name: moneyvibe_clone
description: A financial personality assessment app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0

  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  dio: ^5.4.0
  glass_kit: ^3.0.0
  intl: ^0.20.2
  sensors_plus: ^6.0.1
  flutter_markdown: ^0.6.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
